# Homework2 - to Lesson 4.
# Тема “Визуализация данных в Matplotlib”


In [1]:
import numpy as np
import pandas as pd
import matplotlib as m

## **Задание на повторение материала
1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [49]:
a = np.array([i for i in range (12,24,1)], dtype = int)

3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [93]:
b1 = a.copy().reshape(3,-1)
b2 = a.copy().reshape(4,-1)
b3 = a.copy().reshape(6,-1)
b4 = a.copy().reshape(-1,6)
b5 = a.copy().reshape(-1,1)

In [94]:
print(f'Размерность массивов {b1.ndim}')

Размерность массивов 2


In [95]:
b1.ndim == b2.ndim == b3.ndim == b4.ndim == b5.ndim

True

4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [107]:
b = np.arange(0,12,1)

In [115]:
print('Размерность запрашиваемого массива {}.\nОТВЕТ:НЕЛЬЗЯ'.format((b.reshape(12,1)).ndim))

Размерность запрашиваемого массива 2.
ОТВЕТ:НЕЛЬЗЯ


5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением,равным 1.0.
    -  Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [116]:
c = np.random.randn(3,4)

In [117]:
c

array([[ 1.33179906,  1.514841  ,  0.95092009, -1.96747395],
       [ 0.41519528,  1.15301226,  1.4046358 , -0.9836795 ],
       [ 0.95407105,  1.22720619,  0.43103305, -0.85360282]])

In [118]:
c.size

12

In [125]:
c1 = c.flatten()

In [128]:
c1.size == c.size

True

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2

In [138]:
a = np.arange(0,21,2)

In [139]:
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [140]:
a = a[::-1]

In [141]:
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2,  0])

7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2.
    - В чем разница между массивами a и b?

In [145]:
b = np.arange(2,21,2)

In [146]:
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [150]:
b = b[::-1]

In [151]:
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Не особо понятно,в чем фокус.Наверно не стоит использовать реверс,но я не вспонил как можно сделать лучше. А разница,в том, что не включается нудевое значение во втором случае.

In [155]:
b.size == a.size

False

### 

8. Вертикально соединить массивы a и b. 
    - a - двумерный массив из нулей, 
    - b - двумерный массив, состоящий из единиц.
    - число строк массива "a" больше 1й и на 1у меньше, чем число строк двумерного массива "b"
    
    Итоговый массив v должен иметь атрибут size, равный 10.

In [195]:
n = 3 #число строк в массиве b
s = 2 # для соединения массиво вертикально,число столбцов должно совпадать

a = np.zeros((n-1,s))
b = np.ones((n,s))

In [196]:
a

array([[0., 0.],
       [0., 0.]])

In [197]:
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [198]:
v = np.vstack((a,b))

In [199]:
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [200]:
v.size

10

### 

9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.
- Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy),состоящая из 4 строк и 3 столбцов. 
- Получить матрицу At путем транспонирования матрицы A.
- Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.

Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и
почему?

In [204]:
a = np.arange(0,12,1,dtype = int)

In [205]:
A = a.copy().reshape(4,3)

In [224]:
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [220]:
At = A.copy().transpose # проверка метода транспонирования

In [221]:
At

<function ndarray.transpose>

In [218]:
At = A.copy().T # проверка аттрибута транспонирования (позволяет отобразить матрицу)

In [219]:
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [222]:
At = np.transpose(A.copy()) # проверка функции транспонирования (позволяет отобразить матрицу)

In [223]:
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [225]:
print('Размерность А  - {}'.format(A.shape))
print('Размерность Аt - {}'.format(At.shape))

Размерность А  - (4, 3)
Размерность Аt - (3, 4)


Число столбцов  матрицы А сопадает с числом строк матрицы Аt, и получится матрица размером (4 х 4) -квадратная

In [228]:
B = A.dot(At)

In [229]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [231]:
B.shape

(4, 4)

Для существования матрицы B сущесвовали как левая, так и правая обратные матрицы равные друг другу, необходимо идостаточно,чтобы определитель матцы B был отличен от нуля 

In [232]:
det_B = np.linalg.det(B)

In [233]:
det_B

0.0

ОТВЕТ: Определитель равен нулю, что  показывает, что обратной матрицы к матрице B не существует.

### 

10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42

In [265]:
np.random.seed(42)

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [304]:
c = np.sort(np.random.randint(0,16,16))

In [297]:
c

array([ 2,  2,  2,  3,  4,  4,  6,  6,  6,  8,  8, 11, 13, 13, 14, 15])

In [305]:
c.ndim

1

In [306]:
c.size

16

12. Поменяйте его форму так, чтобы получилась квадратная матрица C. 
    - Получите матрицу D,поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.
    - Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [307]:
C = c.reshape(int(np.sqrt(c.size)),int(np.sqrt(c.size)))

In [308]:
C

array([[ 1,  1,  1,  3],
       [ 3,  4,  6,  8],
       [ 8,  9,  9, 11],
       [11, 11, 13, 14]])

In [314]:
C = np.dot(C.copy(),10)

In [315]:
C.shape

(4, 4)

In [316]:
B.shape

(4, 4)

In [317]:
D = np.add(B,C)

In [318]:
D

array([[ 105,  114,  123,  332],
       [ 314,  450,  686,  922],
       [ 823,  986, 1049, 1312],
       [1132, 1222, 1512, 1702]])

In [320]:
det_D =np.linalg.det(D)
print('Определитель матрицы D = {}'.format(det_D))

Определитель матрицы D = 6891300000.000008


In [323]:
D_inv = np.linalg.inv(D)
print('Обратная матрица матрице D :\n{}'.format(D_inv))

Обратная матрица матрице D :
[[ 0.00754763 -0.00544855 -0.00491399  0.00526728]
 [-0.0069817   0.00122662  0.00890006 -0.00616328]
 [-0.00584984  0.00278276 -0.0031278   0.00204472]
 [ 0.00518959  0.00027104 -0.00034313 -0.00030708]]


In [327]:
rank_D = np.linalg.matrix_rank(D_inv)
print('Ранк Обратной матрицы матрице D = {}'.format(rank_D))

Ранк Обратной матрицы матрице D = 4


In [328]:
det_Dinv =np.linalg.det(D_inv)
print('Определитель обратной матрицы матрице D = {}'.format(det_Dinv))

Определитель обратной матрицы матрице D = 1.4511050164700403e-10


13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице.
    - Убедитесь, что в матрице D_inv остались только нули и единицы.
    - С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4. Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [331]:
D_inv[D_inv<0] = 0
D_inv[D_inv>0] = 1

In [332]:
D_inv

array([[1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [1., 1., 0., 0.]])

In [335]:
E = np.where(D_inv, B,C)
print('Матрица B:\n{}'.format(B))
print('Матрица C:\n{}'.format(C))

Матрица B:
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
Матрица C:
[[ 100  100  100  300]
 [ 300  400  600  800]
 [ 800  900  900 1100]
 [1100 1100 1300 1400]]


In [336]:
print('Матрица E:\n{}'.format(E))

Матрица E:
[[   5  100  100   32]
 [ 300   50   86  800]
 [ 800   86  900  212]
 [  32  122 1300 1400]]
